# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
    :database => {
        :box_name => "centos/8",
        :fwd => [
              {guest: 22, host: 62001},
        ],
      }
}


Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s


          boxconfig[:fwd].each do |port|
            box.vm.network "forwarded_port", port
          end

          if boxconfig.key?(:public)
            box.vm.network "public_network", boxconfig[:public]
          end
          
          box.vm.provision "ansible" do |ansible|
            ansible.playbook = "provision.yml"
          end

      end
  end
end
