# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
    :master => {
        :box_name => "centos/7",
        :fwd => [
              {guest: 22, host: 62001},
        ],
        :ip_addr => '192.168.1.100',
      },
    :slave => {
      :box_name => "centos/7",
      :fwd => [
            {guest: 22, host: 62002},
      ],
      :ip_addr => '192.168.1.200',
    },
    :backup => {
      :box_name => "centos/7",
      :fwd => [
            {guest: 22, host: 62003},
      ],
      :ip_addr => '192.168.1.150',
    },
}


Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          boxconfig[:fwd].each do |port|
            box.vm.network "forwarded_port", port
          end

          if boxconfig.key?(:public)
            box.vm.network "public_network", boxconfig[:public]
          end
          
          box.vm.provision "ansible" do |ansible|
            ansible.playbook = "provision.yml"
          end

      end
  end
end
