# -*- mode: ruby -*-
# vim: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "centos/7"

    config.vm.define "web" do |web|
      web.vm.hostname = "web"
      web.vm.network "private_network", ip: "192.168.11.100"  
      web.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
      end 
    end

    config.vm.define "log" do |log|
      log.vm.hostname = "log"
      log.vm.network "private_network", ip: "192.168.11.101"
      log.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
      end
    end

    config.vm.define "elk" do |elk|
      elk.vm.hostname = "elk"
      elk.vm.network "private_network", ip: "192.168.11.102"
      elk.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "4096"]
      end
    end

end