# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :consul => {
        :box_name => "ubuntu/bionic64",
        :ip_addr => '192.168.11.100',
        :fwd => [
              {guest: 22, host: 2222},
        ],
  },
  :pg1 => {
        :box_name => "ubuntu/bionic64",
        :ip_addr => '192.168.11.120',
        :fwd => [
              {guest: 22, host: 2201},
        ],
  },
  :pg2 => {
        :box_name => "ubuntu/bionic64",
        :ip_addr => '192.168.11.121',
        :fwd => [
              {guest: 22, host: 2204},
        ],
  },
  :pg3 => {
        :box_name => "ubuntu/bionic64",
        :ip_addr => '192.168.11.123',
        :fwd => [
              {guest: 22, host: 2210},
        ],
  },
  :haproxy => {
        :box_name => "ubuntu/bionic64",
        :ip_addr => '192.168.11.101',
        :fwd => [
              {guest: 22, host: 2205},
        ],
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          
          boxconfig[:fwd].each do |port|
            box.vm.network "forwarded_port", port
          end

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

      end
  end
end
