# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.define "server" do |server|
   server.vm.hostname = "server"
   server.vm.network "private_network", ip: "192.168.10.10"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "vvv"
    ansible.playbook = "provision.yml"
    ansible.sudo = "true"
  end
end