# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :centos => {
    :box_name => "centos/7",
    :ip_addr => "192.168.11.101",
  },
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s

      #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

      box.vm.network "private_network", ip: boxconfig[:ip_addr]

      box.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "256"]
      end

      box.vm.provision "shell", inline: <<-SHELL
#          mkdir -p ~root/.ssh
#          cp ~vagrant/.ssh/auth* ~root/.ssh
           yum install epel-release -y -q
           yum install wget -y -q
# Install tools for building rpm
           yum install redhat-lsb-core rpmdevtools rpm-build -y -q
           yum install yum-utils wget gcc vim git -y -q
# Install tools for building woth mock and make prepares    
           yum install mock -y -q
           usermod -a -G mock root
# Install tools for creating your own REPO
           yum install createrepo -y -q
# Install docker-ce
           sudo yum install -y -q yum-utils links \
           device-mapper-persistent-data \
           lvm2
           sudo yum-config-manager \
           --add-repo \
           https://download.docker.com/linux/centos/docker-ce.repo
           yum install docker-ce docker-compose -y -q
           systemctl start docker
           docker run hello-world
      SHELL

      box.vm.provision "shell", path: "scripts/01-script.sh"
    end
  end
end
